# https://stackoverflow.com/questions/39475716/undefined-reference-to-boostfilesystempath-traitsconvert
g++ -shared -fPIC -O2 -std=c++17 -o libredgpu_f2.so \
-Isrc/openframeworks \
-Isrc/openframeworks/3d \
-Isrc/openframeworks/app \
-Isrc/openframeworks/communication \
-Isrc/openframeworks/events \
-Isrc/openframeworks/gl \
-Isrc/openframeworks/graphics \
-Isrc/openframeworks/math \
-Isrc/openframeworks/sound \
-Isrc/openframeworks/types \
-Isrc/openframeworks/utils \
-Isrc/openframeworks/video \
-Isrc/glew \
-Isrc/glew/include \
-Isrc/libtess2 \
-Isrc/libtess2/include \
-Isrc/boost \
-Isrc/boost/include \
-Isrc/utf8cpp \
-Isrc/utf8cpp/include \
-Isrc/glm \
-Isrc/glm/include \
-Isrc/json \
-Isrc/json/include \
-Isrc/pugixml \
-Isrc/pugixml/include \
-Isrc/cairo \
-Isrc/cairo/include \
-Isrc/cairo/include/cairo \
-Iaddons/ofxAssimpModelLoader/libs/assimp/include \
-Iofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16 \
-Iofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/examples \
-Iofxaddons/ofxFBX/src \
-Iofxaddons/ofxFBX/src/FBXSource \
-Iofxaddons/ofxFBX/libs/libfbxsdk_2019.5/include \
-Iglfw/include \
redgpu_f2.cpp \
addons/ofxAssimpModelLoader/src/ofxAssimpAnimation.cpp \
addons/ofxAssimpModelLoader/src/ofxAssimpMeshHelper.cpp \
addons/ofxAssimpModelLoader/src/ofxAssimpModelLoader.cpp \
addons/ofxAssimpModelLoader/src/ofxAssimpTexture.cpp \
ofxaddons/ofxFBX/src/ofxFBXAnimation.cpp \
ofxaddons/ofxFBX/src/ofxFBXBone.cpp \
ofxaddons/ofxFBX/src/ofxFBX.cpp \
ofxaddons/ofxFBX/src/ofxFBXMesh.cpp \
ofxaddons/ofxFBX/src/ofxFBXMeshMaterial.cpp \
ofxaddons/ofxFBX/src/ofxFBXNode.cpp \
ofxaddons/ofxFBX/src/ofxFBXNurbsCurve.cpp \
ofxaddons/ofxFBX/src/ofxFBXSkeleton.cpp \
ofxaddons/ofxFBX/src/FBXSource/GetPosition.cxx \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcBone.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcCluster.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcMesh.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcMeshMaterial.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcNode.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcNurbsCurve.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcPose.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcScene.cpp \
ofxaddons/ofxFBX/src/FBXSource/ofxFBXSrcSkeleton.cpp \
ofxaddons/ofxFBX/libs/libfbxsdk_2019.5/include/Common/AnimationUtility.cxx \
ofxaddons/ofxFBX/libs/libfbxsdk_2019.5/include/Common/Common.cxx \
ofxaddons/ofxFBX/libs/libfbxsdk_2019.5/include/Common/GeometryUtility.cxx \
ofxaddons/ofxFirstPersonCamera/src/ofxFirstPersonCamera.cpp \
ofxaddons/ofxManipulator/src/ofxManipulator.cpp \
ofxaddons/ofxRaccoonImGui/libs/cimgui-1.89.9-44769f63d/cimgui.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/examples/imgui_impl_glfw.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/examples/imgui_impl_opengl2.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/examples/imgui_impl_opengl3.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/imgui.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/imgui_demo.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/imgui_draw.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/imgui_widgets.cpp \
ofxaddons/ofxRaccoonImGui/libs/imgui-1.89.9-1d8e48c16/imgui_tables.cpp \
ofxaddons/ofxRaccoonImGui/src/ofxRaccoonImGui.cpp \
ofxaddons/ofxPostProcessing/src/BleachBypassPass.cpp \
ofxaddons/ofxPostProcessing/src/BloomPass.cpp \
ofxaddons/ofxPostProcessing/src/ContrastPass.cpp \
ofxaddons/ofxPostProcessing/src/ConvolutionPass.cpp \
ofxaddons/ofxPostProcessing/src/DofAltPass.cpp \
ofxaddons/ofxPostProcessing/src/DofPass.cpp \
ofxaddons/ofxPostProcessing/src/EdgePass.cpp \
ofxaddons/ofxPostProcessing/src/FakeSSSPass.cpp \
ofxaddons/ofxPostProcessing/src/FxaaPass.cpp \
ofxaddons/ofxPostProcessing/src/GodRaysPass.cpp \
ofxaddons/ofxPostProcessing/src/HorizontalTiltShifPass.cpp \
ofxaddons/ofxPostProcessing/src/HsbShiftPass.cpp \
ofxaddons/ofxPostProcessing/src/KaleidoscopePass.cpp \
ofxaddons/ofxPostProcessing/src/LimbDarkeningPass.cpp \
ofxaddons/ofxPostProcessing/src/LUTPass.cpp \
ofxaddons/ofxPostProcessing/src/NoiseWarpPass.cpp \
ofxaddons/ofxPostProcessing/src/PixelatePass.cpp \
ofxaddons/ofxPostProcessing/src/PostProcessing.cpp \
ofxaddons/ofxPostProcessing/src/RenderPass.cpp \
ofxaddons/ofxPostProcessing/src/RGBShiftPass.cpp \
ofxaddons/ofxPostProcessing/src/RimHighlightingPass.cpp \
ofxaddons/ofxPostProcessing/src/SSAOPass.cpp \
ofxaddons/ofxPostProcessing/src/ToonPass.cpp \
ofxaddons/ofxPostProcessing/src/VerticalTiltShifPass.cpp \
ofxaddons/ofxPostProcessing/src/ZoomBlurPass.cpp \
ofxaddons/ofxPostProcessingExtra/GenericPass.cpp \

